name: Acromere Website CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

env:
  ACM_CI_USERNAME: ${{ secrets.ACM_CI_USERNAME }}
  ACM_CI_PASSWORD: ${{ secrets.ACM_CI_PASSWORD }}
  ACM_GPG_PASSWORD: ${{ secrets.ACM_GPG_PASSWORD }}
  ACM_KEYSTORE_PASSWORD: ${{ secrets.ACM_KEYSTORE_PASSWORD }}
  ACM_REPO_USERNAME: ${{ secrets.ACM_REPO_USERNAME }}
  ACM_REPO_PASSWORD: ${{ secrets.ACM_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "25"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  resources:
    name: Resources
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Fetch CI/CD resources
        uses: actions/checkout@v6
        with:
          repository: acromere/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required to render the product icon
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}

  client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Fetch CI/CD resources
        uses: actions/checkout@v6
        with:
          repository: acromere/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: NPM Repository Cache
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build Client
        run: |
          rm -rf dist/
          npm install
          npm run build
          cd dist
          zip -r ../client.zip *
          cd -

      - name: Copy Client ZIP
        run: scp -B client.zip ${{env.ACM_CI_USERNAME}}@acromere.com:/opt/acm/repo/latest/www.acromere.com/client.zip

      #      - name: Copy Provider Icon
      #        run: |
      #          scp -B server/target/main/images/acromere.png ${{env.ACM_CI_USERNAME}}@acromere.com:/opt/acm/repo/stable/acromere/provider.png
      #          scp -B server/target/main/images/acromere-dark.png ${{env.ACM_CI_USERNAME}}@acromere.com:/opt/acm/repo/stable/acromere/provider-dark.png
      #          scp -B server/target/main/images/acromere-light.png ${{env.ACM_CI_USERNAME}}@acromere.com:/opt/acm/repo/stable/acromere/provider-light.png

      - name: Update the Website Client
        run: ssh ${{env.ACM_CI_USERNAME}}@acromere.com bin/update-acromere-website-client

  server:
    name: Server
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Fetch CI/CD resources
        uses: actions/checkout@v6
        with:
          repository: acromere/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      # Required to render the product icon
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Build Server
        run: |
          mvn ${{env.MAVEN_PARMS}} package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      - name: Copy Server JAR
        run: scp -B target/acromere.jar ${{env.ACM_CI_USERNAME}}@acromere.com:/opt/acm/repo/latest/www.acromere.com/server.jar
